apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-python-basic-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubernetes-python-basic-app
  template:
    metadata:
      labels:
        app: kubernetes-python-basic-app
    spec:
      containers:
      - name: kubernetes-python-basic-app
        image: kubernetes-python-basic-app:latest
        # Remove this if actually hosting the image in a remote repo
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
